# This file was generated by GoReleaser. DO NOT EDIT.
cask "anvil" do
  name "anvil"
  desc "CLI and MCP server for the Sable AI voice agent platform"
  homepage "https://github.com/sable-inc/anvil"
  version "0.3.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "anvil"

  on_macos do
    on_intel do
      url "https://github.com/sable-inc/anvil/releases/download/v#{version}/anvil_#{version}_darwin_amd64.tar.gz"
      sha256 "a5ef6f81c1b18685562a7b5e314996294d0ad0491b02824b26d2cc1bb5d62f52"
    end
    on_arm do
      url "https://github.com/sable-inc/anvil/releases/download/v#{version}/anvil_#{version}_darwin_arm64.tar.gz"
      sha256 "9d4ab16ba73fdd4fa241d44af4360ee7163f49c8b4c1a20c2664aabf8e86f9b1"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/sable-inc/anvil/releases/download/v#{version}/anvil_#{version}_linux_amd64.tar.gz"
      sha256 "f19e1f915f32bafe68d262a6df5beb6159f7bbd38e744ff3d431ce4cec03be3f"
    end
    on_arm do
      url "https://github.com/sable-inc/anvil/releases/download/v#{version}/anvil_#{version}_linux_arm64.tar.gz"
      sha256 "2c479458953a3b096a13d2fcba810eefbc2848748b970f6f3aea620aec81ccdc"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/anvil"]
    end
  end

  # No zap stanza required
end
