# This file was generated by GoReleaser. DO NOT EDIT.
cask "anvil" do
  name "anvil"
  desc "CLI and MCP server for the Sable AI voice agent platform"
  homepage "https://github.com/sable-inc/anvil"
  version "0.2.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "anvil"

  on_macos do
    on_intel do
      url "https://github.com/sable-inc/anvil/releases/download/v#{version}/anvil_#{version}_darwin_amd64.tar.gz"
      sha256 "e846332b8fe22f61f66132fc806bd4c444d0c8c45e87856588c9c132f97dcb4f"
    end
    on_arm do
      url "https://github.com/sable-inc/anvil/releases/download/v#{version}/anvil_#{version}_darwin_arm64.tar.gz"
      sha256 "0245008083b06862ac9a9b0f92e3244a9f99d53cb3c53ff3a12fdb4aafe43bcc"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/sable-inc/anvil/releases/download/v#{version}/anvil_#{version}_linux_amd64.tar.gz"
      sha256 "fccd31b55b9c732b2de04fc3e6ddf25e2a6b2275cba687b2f738d674530800c5"
    end
    on_arm do
      url "https://github.com/sable-inc/anvil/releases/download/v#{version}/anvil_#{version}_linux_arm64.tar.gz"
      sha256 "8fa5b96bdba253d4c9e7bd0c205ff8657c380b6f62cc37d6fbbb1c8799e92297"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/anvil"]
    end
  end

  # No zap stanza required
end
