# This file was generated by GoReleaser. DO NOT EDIT.
cask "anvil" do
  name "anvil"
  desc "CLI and MCP server for the Sable AI voice agent platform"
  homepage "https://github.com/sable-inc/anvil"
  version "0.2.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "anvil"

  on_macos do
    on_intel do
      url "https://github.com/sable-inc/anvil/releases/download/v#{version}/anvil_#{version}_darwin_amd64.tar.gz"
      sha256 "1cb67f288d16cb9b60ff6e4e3c5d1e31103271cec1a6893f34d29a162e44e360"
    end
    on_arm do
      url "https://github.com/sable-inc/anvil/releases/download/v#{version}/anvil_#{version}_darwin_arm64.tar.gz"
      sha256 "8732ccdcf09ea11f9f2cbd42ea6be05015c66a235695a08ceeb70d9754ef208b"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/sable-inc/anvil/releases/download/v#{version}/anvil_#{version}_linux_amd64.tar.gz"
      sha256 "f867052c896a0b3ecea614b17e3ef1143427c180c56c6684297c20e6d66c87c7"
    end
    on_arm do
      url "https://github.com/sable-inc/anvil/releases/download/v#{version}/anvil_#{version}_linux_arm64.tar.gz"
      sha256 "1c3ef04dbd9bb7e0d23b659d0a953fa150132ecc3d8c54aaa16393dc82940043"
    end
  end

  # No zap stanza required
end
